package dto

// Code generated by a tool. DO NOT EDIT.
// Additions may be hand-coded in a separate go-file.
// https://sqldalmaker.sourceforge.net/

// ProjectLi list item: [+] p_tasks_count
type ProjectLi struct {
	PId         int64  `json:"p_id"`
	PName       string `json:"p_name"`
	PTasksCount int64  `json:"p_tasks_count"`
}
