package dto

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

// ProjectLi list item: [+] p_tasks_count
type ProjectLi struct {
	PID         int64  `json:"p_id"`
	PName       string `json:"p_name"`
	PTasksCount int64
}
