package dbal

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

import (
	"context"
	"sdm_demo_todolist/no_orm/dbal/dto"
)

type ProjectsDao2 struct {
	ds DataStore
}

func (dao *ProjectsDao2) ReadProjectList(ctx context.Context) (res []*dto.Project, err error) {
	sql := `select * from projects`
	errMap := make(map[string]int)
	_onRow := func(row map[string]interface{}) {
		item := dto.Project{}
		SetInt64(&item.PID, row, "p_id", errMap)
		SetString(&item.PName, row, "p_name", errMap)
		res = append(res, &item)
	}
	err = dao.ds.QueryAllRows(ctx, sql, _onRow)
	if err == nil {
		err = ErrMapToErr(errMap)
	}
	return
}
