package models

// Code generated by a tool. DO NOT EDIT.
// Additions may be hand-coded in a separate go-file.
// https://sqldalmaker.sourceforge.net/

type Project struct {
	PId   int64  `json:"p_id" gorm:"column:p_id;primaryKey;autoIncrement"`
	PName string `json:"p_name" gorm:"column:p_name;not null"`
}
