package models

// Code generated by a tool. DO NOT EDIT.
// Additions may be hand-coded in a separate go-file.
// https://sqldalmaker.sourceforge.net/

// TaskLi: a `target` list item having no "t_comments"
type TaskLi struct {
	TId       int64  `json:"t_id" gorm:"column:t_id;primaryKey;autoIncrement"`
	PId       int64  `json:"p_id" gorm:"column:p_id"`
	TPriority int64  `json:"t_priority" gorm:"column:t_priority;not null"`
	TDate     string `json:"t_date" gorm:"column:t_date;not null"`
	TSubject  string `json:"t_subject" gorm:"column:t_subject;not null"`
}
