package dto

// Code generated by a tool. DO NOT EDIT.
// Additions may be hand-coded in a separate go-file.
// https://sqldalmaker.sourceforge.net/

type Project struct {
	PId   int64  `json:"p_id" db:"p_id"`
	PName string `json:"p_name" db:"p_name"`
}
